name: MS SQL Server CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mssql-test:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
          - 1433:1433
        options: >-
          --env ACCEPT_EULA=Y
          --env SA_PASSWORD=YourPassword123!
          --health-cmd "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourPassword123!' -Q 'SELECT 1'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Wait for MS SQL Server to be ready
      run: |
        for i in {1..30}; do
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourPassword123!' -Q "SELECT 1" && break || sleep 2;
        done

    - name: Create database and table
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourPassword123!' -Q "CREATE DATABASE TestDB;"
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourPassword123!' -d TestDB -Q "CREATE TABLE TestTable (id INT PRIMARY KEY, name NVARCHAR(50));"

    - name: Insert and query data
      run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourPassword123!' -d TestDB -Q "INSERT INTO TestTable VALUES (1, 'GitHub Actions');"
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourPassword123!' -d TestDB -Q "SELECT * FROM TestTable;"

    - name: Check container logs
      run: docker logs $(docker ps -q --filter "ancestor=mcr.microsoft.com/mssql/server:2022-latest")

